### ISSUE TITLE
Plugin is causing mashup editor not loading in Thingworx 9.0

### ISSUE THREAD

**Issue by psychodracon** [ptc-iot-sharing/MonacoEditorTWX#12]
While using Thingworx 9.0 there is no possibility to load mashup editor in composer, those errors appears, after removing extension everything goes back to normal
![image](https://user-images.githubusercontent.com/45995079/90627436-371f9600-e21c-11ea-8776-38f3b926536f.png)
![image](https://user-images.githubusercontent.com/45995079/90627460-41da2b00-e21c-11ea-814e-c54c7a8aca96.png)

**Comment by stefan-lacatus** [comment]
Thanks for reporting this.

Expect an update during next week that fixes this compatibility issues.
