### ISSUE TITLE
Collection widget bindings

### ISSUE THREAD

**Issue by wlhaynes** [ptc-iot-sharing/MonacoEditorTWX#24]
Loving this extension! One of my fellow devs noticed an issue with editing MashupPropertyBinding and MashupGlobalPropertyBinding properties of a collection widget. Only about half a row of the editor is visible, and we don't see any way to resize it. We're working around this by simple disabling the TamperMonkey script when we need to access these properties.

![binding](https://user-images.githubusercontent.com/49765801/121692935-9c3bc500-ca96-11eb-878a-ee97074e5e10.png)

**Comment by stefan-lacatus** [comment]
I'll try to take a look at this next week.

What is the thingworx version you are running?

**Comment by wlhaynes** [comment]
we're currently 8.5.4

Thanks!
