### ISSUE TITLE
Unable to edit thing after opening it in read-only mode.

### ISSUE THREAD

**Issue by Radurer** [ptc-iot-sharing/MonacoEditorTWX#35]
When opening a thing and seeing that a different user is accessing it, I am clicking cancel just to see the thing in read-only mode. However, when doing so, the "Edit" button of the entity is fully disabled, and can only be re-enabled when selecting another entity and going back to the initial entity.

This issue was not reproductible in 0.1, but it is in 0.3

Thingworx version is 9.2.1

**Comment by stefan-lacatus** [comment]
I've looked into this now, and I'm afraid this is a ThingWorx bug that can be reproduced 100% of the time without MonacoEditorTwx enabled.

Feel free to validate that the same happens to you, and, I'm afraid you'll have to request a fix from PTC Support.
