### ISSUE TITLE
What's the use of thingworx's anomaly detection？

### ISSUE THREAD

**Issue by KAHML** [ptc-iot-sharing/MonacoEditorTWX#40]
hello，I am a new girl, I have a question to ask you.What's the use of thingworx's anomaly detection? It feels like I'm collecting my own data and building a model. What can I do? Do I set the upper and lower limits and then figure out what the difference is between the exception and what it's trained to do?

**Comment by stefan-lacatus** [comment]
Hello. 
This project is for the `Monaco Editor for Thingworx`, an extension improving the development experience while writing services inside Thingwrox Composer.
Your question is more general about Thingworx, and has nothing to do with this project.

I'd recommend looking at the PTC Community forums (https://community.ptc.com/) where such a question would be more appropiate.

**Comment by KAHML** [comment]
Thank you very much for your reply. Your answer is very helpful to me. Thank you again!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ptc-iot-sharing/MonacoEditorTWX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 凌晨1:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ptc-iot-sharing/MonacoEditorTWX] What's the use of thingworx's anomaly detection？ (Issue #40)





 
Hello.
 This project is for the Monaco Editor for Thingworx, an extension improving the development experience while writing services inside ThingWorx Composer.
 Your question is more general about Thingworx, and has nothing to do with this project.
 
I'd recommend looking at the PTC Community forums (https://community.ptc.com/) where such a question would be more appropriate.
