### ISSUE TITLE
Creating a function containing a code panel initially displays it as blank.

### ISSUE THREAD

**Issue by Radurer** [ptc-iot-sharing/MonacoEditorTWX#42]
When creating a new function in a mashup that contains code (validator/expression etc.), the code screen appears blank, like so:

![image](https://user-images.githubusercontent.com/57625103/178204044-a0166bf8-7573-4403-9e88-ee81ba42d488.png)

When closing and reopening, it is not reoccurring.

Issue in DevTools:

![image](https://user-images.githubusercontent.com/57625103/178204288-78ad6225-ec82-45b5-a6f4-3ace4465682a.png)

**Comment by stefan-lacatus** [comment]
I check this out. I've actually encountered the issue before. 

As a workaround, it's usually solved after you open up the expression a second time.

So, if you initially create the expression, you cannot directly start typing in the code. But, if you close it out, and open it again, the editor would be initialized correctly.
