### ISSUE TITLE
Question: For the latest version, code formats itself after pasting.

### ISSUE THREAD

**Issue by Radurer** [ptc-iot-sharing/MonacoEditorTWX#49]
For example, I have this structure:

`let presentStatus = isPresent ? ("Not Present") : ("Actually Present.");`

If I copy the string `"Absent"` and paste it in the true condition inside the parentheses, the parentheses disappear for the whole expression and the rest of the code is also formatted. This is because the code autoformats after pasting (CTRL+V).

One more thing that happens is indentation changes from TAB to space. How can autoformatting be disabled? Thank you!

**Comment by stefan-lacatus** [comment]
Yes, auto format can be configured:
1. 
![image](https://user-images.githubusercontent.com/6620014/213463138-e8ef7a2d-9d10-47ba-ba7d-2a2e2a3ff756.png)

2. 
![image](https://user-images.githubusercontent.com/6620014/213463254-dd1f6304-4708-4869-bca7-8b730ba9d333.png)

3. 
![image](https://user-images.githubusercontent.com/6620014/213463463-ecbdc4d0-628b-4a98-8768-76b04b059345.png)

4. Click outside to save the configuration
