### ISSUE TITLE
It displays TypeScript language in Javscript mode

### ISSUE THREAD

**Issue by tdhung80** [ptc-iot-sharing/MonacoEditorTWX#54]
Hi,

How can I turn off TypeScript in Javascript mode, I just want to see the pure javascript code during development.

![image](https://github.com/ptc-iot-sharing/MonacoEditorTWX/assets/2413747/fa6259c4-0447-43de-84fb-48d3ed4a7814)

In the image, text in gray should not appear in Javascript mode

Regards,
Hung Tran

**Comment by stefan-lacatus** [comment]
This can be easily disabled using the built in configuration manager.

Open it (either using the shortcut `ctrl + \` or using the command palette (`F1`), type `view configuration`.

Then, switch `inlayHints.enabled` to `false`.
