### ISSUE TITLE
"Backwards" writing in TypeScript

### ISSUE THREAD

**Issue by JensCarmbrant** [ptc-iot-sharing/MonacoEditorTWX#55]
Hello,

I wanted to give writing TypeScript in Thingworx a shot using the Monaco editor.
However, I am facing some very strange issue.

As soon as I switch to TypeScript (using F1 -> Switch to TypeScript), my cursor ends up on the first row (column 1, row 1), and if I start typing, the characters are "pushed" to the right (could be because of the cursor always ends up at column 1, row 1).

Please see the short video to see the issue.
Not sure if this is a bug in the editor, or if there is something else going on.

[2024-01-04 10-46-43.webm](https://github.com/ptc-iot-sharing/MonacoEditorTWX/assets/123723246/98f95858-fb29-4bda-8062-ea778e09d642)

Any insight would be highly appreciated.
Regards,
Jens

**Comment by stefan-lacatus** [comment]
Hello Jens,

Sorry for the late reply. 
The Typescript support in services has not been tested in a really long time. Please consider that functionality as being experimental. I'll look into it next week

**Comment by JensCarmbrant** [comment]
Hello Petrisor,

No worries I just wanted to bring it to your attention and perhaps see if there were anyone else having the same issues.
Tale the time you need!
